import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <Link  href={'/'}>
              <li>home</li>
            </Link>
            <Link  href={"/store"}>
              <li>categorie</li>
            </Link>
          </ul>
        </nav>
        {children}
        </body>
    </html>
  );
}
